/* This file was generated by SableCC (http://www.sablecc.org/). */

package tony.node;

import java.util.*;
import tony.analysis.*;

public final class ACallCall extends PCall
{
    private TId _id_;
    private final LinkedList _realParList_ = new TypedLinkedList(new RealParList_Cast());

    public ACallCall()
    {
    }

    public ACallCall(
        TId _id_,
        List _realParList_)
    {
        setId(_id_);

        {
            this._realParList_.clear();
            this._realParList_.addAll(_realParList_);
        }

    }
    public Object clone()
    {
        return new ACallCall(
            (TId) cloneNode(_id_),
            cloneList(_realParList_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACallCall(this);
    }

    public TId getId()
    {
        return _id_;
    }

    public void setId(TId node)
    {
        if(_id_ != null)
        {
            _id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _id_ = node;
    }

    public LinkedList getRealParList()
    {
        return _realParList_;
    }

    public void setRealParList(List list)
    {
        _realParList_.clear();
        _realParList_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_id_)
            + toString(_realParList_);
    }

    void removeChild(Node child)
    {
        if(_id_ == child)
        {
            _id_ = null;
            return;
        }

        if(_realParList_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        for(ListIterator i = _realParList_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class RealParList_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PRealParList node = (PRealParList) o;

            if((node.parent() != null) &&
                (node.parent() != ACallCall.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != ACallCall.this))
            {
                node.parent(ACallCall.this);
            }

            return node;
        }
    }
}
