/* This file was generated by SableCC (http://www.sablecc.org/). */

package tony.node;

import java.util.*;
import tony.analysis.*;

public final class AHeader extends PHeader
{
    private final LinkedList _type_ = new TypedLinkedList(new Type_Cast());
    private TId _id_;
    private final LinkedList _parameters_ = new TypedLinkedList(new Parameters_Cast());

    public AHeader()
    {
    }

    public AHeader(
        List _type_,
        TId _id_,
        List _parameters_)
    {
        {
            this._type_.clear();
            this._type_.addAll(_type_);
        }

        setId(_id_);

        {
            this._parameters_.clear();
            this._parameters_.addAll(_parameters_);
        }

    }
    public Object clone()
    {
        return new AHeader(
            cloneList(_type_),
            (TId) cloneNode(_id_),
            cloneList(_parameters_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAHeader(this);
    }

    public LinkedList getType()
    {
        return _type_;
    }

    public void setType(List list)
    {
        _type_.clear();
        _type_.addAll(list);
    }

    public TId getId()
    {
        return _id_;
    }

    public void setId(TId node)
    {
        if(_id_ != null)
        {
            _id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _id_ = node;
    }

    public LinkedList getParameters()
    {
        return _parameters_;
    }

    public void setParameters(List list)
    {
        _parameters_.clear();
        _parameters_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_type_)
            + toString(_id_)
            + toString(_parameters_);
    }

    void removeChild(Node child)
    {
        if(_type_.remove(child))
        {
            return;
        }

        if(_id_ == child)
        {
            _id_ = null;
            return;
        }

        if(_parameters_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        for(ListIterator i = _type_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(_id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        for(ListIterator i = _parameters_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class Type_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PType node = (PType) o;

            if((node.parent() != null) &&
                (node.parent() != AHeader.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AHeader.this))
            {
                node.parent(AHeader.this);
            }

            return node;
        }
    }

    private class Parameters_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PParameters node = (PParameters) o;

            if((node.parent() != null) &&
                (node.parent() != AHeader.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AHeader.this))
            {
                node.parent(AHeader.this);
            }

            return node;
        }
    }
}
