/* This file was generated by SableCC (http://www.sablecc.org/). */

package tony.node;

import java.util.*;
import tony.analysis.*;

public final class AMultiIdListIdentifierList extends PIdentifierList
{
    private TId _id_;
    private PIdentifierList _identifierList_;

    public AMultiIdListIdentifierList()
    {
    }

    public AMultiIdListIdentifierList(
        TId _id_,
        PIdentifierList _identifierList_)
    {
        setId(_id_);

        setIdentifierList(_identifierList_);

    }
    public Object clone()
    {
        return new AMultiIdListIdentifierList(
            (TId) cloneNode(_id_),
            (PIdentifierList) cloneNode(_identifierList_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultiIdListIdentifierList(this);
    }

    public TId getId()
    {
        return _id_;
    }

    public void setId(TId node)
    {
        if(_id_ != null)
        {
            _id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _id_ = node;
    }

    public PIdentifierList getIdentifierList()
    {
        return _identifierList_;
    }

    public void setIdentifierList(PIdentifierList node)
    {
        if(_identifierList_ != null)
        {
            _identifierList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _identifierList_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_id_)
            + toString(_identifierList_);
    }

    void removeChild(Node child)
    {
        if(_id_ == child)
        {
            _id_ = null;
            return;
        }

        if(_identifierList_ == child)
        {
            _identifierList_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(_identifierList_ == oldChild)
        {
            setIdentifierList((PIdentifierList) newChild);
            return;
        }

    }
}
