/* This file was generated by SableCC (http://www.sablecc.org/). */

package tony.node;

import java.util.*;
import tony.analysis.*;

public final class AVarDefinition extends PVarDefinition
{
    private PType _type_;
    private PIdentifierList _identifierList_;

    public AVarDefinition()
    {
    }

    public AVarDefinition(
        PType _type_,
        PIdentifierList _identifierList_)
    {
        setType(_type_);

        setIdentifierList(_identifierList_);

    }
    public Object clone()
    {
        return new AVarDefinition(
            (PType) cloneNode(_type_),
            (PIdentifierList) cloneNode(_identifierList_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVarDefinition(this);
    }

    public PType getType()
    {
        return _type_;
    }

    public void setType(PType node)
    {
        if(_type_ != null)
        {
            _type_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _type_ = node;
    }

    public PIdentifierList getIdentifierList()
    {
        return _identifierList_;
    }

    public void setIdentifierList(PIdentifierList node)
    {
        if(_identifierList_ != null)
        {
            _identifierList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _identifierList_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_type_)
            + toString(_identifierList_);
    }

    void removeChild(Node child)
    {
        if(_type_ == child)
        {
            _type_ = null;
            return;
        }

        if(_identifierList_ == child)
        {
            _identifierList_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_type_ == oldChild)
        {
            setType((PType) newChild);
            return;
        }

        if(_identifierList_ == oldChild)
        {
            setIdentifierList((PIdentifierList) newChild);
            return;
        }

    }
}
