/* This file was generated by SableCC (http://www.sablecc.org/). */

package tony.node;

import tony.analysis.*;

public final class TBiggerEqual extends Token
{
    public TBiggerEqual()
    {
        super.setText(">=");
    }

    public TBiggerEqual(int line, int pos)
    {
        super.setText(">=");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TBiggerEqual(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTBiggerEqual(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TBiggerEqual text.");
    }
}
