/* This file was generated by SableCC (http://www.sablecc.org/). */

package tony.node;

import tony.analysis.*;

public final class TCommentEnd extends Token
{
    public TCommentEnd()
    {
        super.setText("*>");
    }

    public TCommentEnd(int line, int pos)
    {
        super.setText("*>");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TCommentEnd(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTCommentEnd(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TCommentEnd text.");
    }
}
