/* This file was generated by SableCC (http://www.sablecc.org/). */

package tony.node;

import tony.analysis.*;

public final class TNilQuestionMark extends Token
{
    public TNilQuestionMark()
    {
        super.setText("nil?");
    }

    public TNilQuestionMark(int line, int pos)
    {
        super.setText("nil?");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TNilQuestionMark(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTNilQuestionMark(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TNilQuestionMark text.");
    }
}
