/* This file was generated by SableCC (http://www.sablecc.org/). */

package tony.node;

import tony.analysis.*;

public final class TSharp extends Token
{
    public TSharp()
    {
        super.setText("#");
    }

    public TSharp(int line, int pos)
    {
        super.setText("#");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TSharp(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSharp(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TSharp text.");
    }
}
