/* This file was generated by SableCC (http://www.sablecc.org/). */

package tony.node;

import tony.analysis.*;

public final class TSmaller extends Token
{
    public TSmaller()
    {
        super.setText("<");
    }

    public TSmaller(int line, int pos)
    {
        super.setText("<");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TSmaller(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSmaller(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TSmaller text.");
    }
}
