/* This file was generated by SableCC (http://www.sablecc.org/). */

package tony.lexer;

import java.io.*;
import java.util.*;
import tony.node.*;

public class Lexer
{
    protected Token token;
    protected State state = State.NORMAL;

    private PushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    protected void filter() throws LexerException, IOException
    {
    }

    public Lexer(PushbackReader in)
    {
        this.in = in;

        if(gotoTable == null)
        {
            try
            {
                DataInputStream s = new DataInputStream(
                    new BufferedInputStream(
                    Lexer.class.getResourceAsStream("lexer.dat")));

                // read gotoTable
                int length = s.readInt();
                gotoTable = new int[length][][][];
                for(int i = 0; i < gotoTable.length; i++)
                {
                    length = s.readInt();
                    gotoTable[i] = new int[length][][];
                    for(int j = 0; j < gotoTable[i].length; j++)
                    {
                        length = s.readInt();
                        gotoTable[i][j] = new int[length][3];
                        for(int k = 0; k < gotoTable[i][j].length; k++)
                        {
                            for(int l = 0; l < 3; l++)
                            {
                                gotoTable[i][j][k][l] = s.readInt();
                            }
                        }
                    }
                }

                // read accept
                length = s.readInt();
                accept = new int[length][];
                for(int i = 0; i < accept.length; i++)
                {
                    length = s.readInt();
                    accept[i] = new int[length];
                    for(int j = 0; j < accept[i].length; j++)
                    {
                        accept[i][j] = s.readInt();
                    }
                }

                s.close();
            }
            catch(Exception e)
            {
                throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
            }
        }
    }

    public Token peek() throws LexerException, IOException
    {
        while(token == null)
        {
            token = getToken();
            filter();
        }

        return token;
    }

    public Token next() throws LexerException, IOException
    {
        while(token == null)
        {
            token = getToken();
            filter();
        }

        Token result = token;
        token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = pos;
        int start_line = line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        int[][][] gotoTable = this.gotoTable[state.id()];
        int[] accept = this.accept[state.id()];
        text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(cr)
                    {
                        cr = false;
                    }
                    else
                    {
                        line++;
                        pos = 0;
                    }
                    break;
                case 13:
                    line++;
                    pos = 0;
                    cr = true;
                    break;
                default:
                    pos++;
                    cr = false;
                    break;
                };

                text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        int middle = (low + high) / 2;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = text.length();
                    accept_pos = pos;
                    accept_line = line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            Token token = new0(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            switch(state.id())
                            {
                                case 1: state = State.COMMENT; break;
                                case 0: state = State.COMMENT; break;
                            }
                            return token;
                        }
                    case 1:
                        {
                            Token token = new1(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            switch(state.id())
                            {
                                case 1: state = State.COMMENT; break;
                            }
                            return token;
                        }
                    case 2:
                        {
                            Token token = new2(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            switch(state.id())
                            {
                                case 1: state = State.COMMENT; break;
                            }
                            return token;
                        }
                    case 3:
                        {
                            Token token = new3(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            switch(state.id())
                            {
                                case 1: state = State.COMMENT; break;
                            }
                            return token;
                        }
                    case 4:
                        {
                            Token token = new4(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            switch(state.id())
                            {
                                case 1: state = State.COMMENT; break;
                            }
                            return token;
                        }
                    case 5:
                        {
                            Token token = new5(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 6:
                        {
                            Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 7:
                        {
                            Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 8:
                        {
                            Token token = new8(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 9:
                        {
                            Token token = new9(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 10:
                        {
                            Token token = new10(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 11:
                        {
                            Token token = new11(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 12:
                        {
                            Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 13:
                        {
                            Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 14:
                        {
                            Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 15:
                        {
                            Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 16:
                        {
                            Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 17:
                        {
                            Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 18:
                        {
                            Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 19:
                        {
                            Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 20:
                        {
                            Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 21:
                        {
                            Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 22:
                        {
                            Token token = new22(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 23:
                        {
                            Token token = new23(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 24:
                        {
                            Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 25:
                        {
                            Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 26:
                        {
                            Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 27:
                        {
                            Token token = new27(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 28:
                        {
                            Token token = new28(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 29:
                        {
                            Token token = new29(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 30:
                        {
                            Token token = new30(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 31:
                        {
                            Token token = new31(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 32:
                        {
                            Token token = new32(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 33:
                        {
                            Token token = new33(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 34:
                        {
                            Token token = new34(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 35:
                        {
                            Token token = new35(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 36:
                        {
                            Token token = new36(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 37:
                        {
                            Token token = new37(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 38:
                        {
                            Token token = new38(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 39:
                        {
                            Token token = new39(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 40:
                        {
                            Token token = new40(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 41:
                        {
                            Token token = new41(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 42:
                        {
                            Token token = new42(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 43:
                        {
                            Token token = new43(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 44:
                        {
                            Token token = new44(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 45:
                        {
                            Token token = new45(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 46:
                        {
                            Token token = new46(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 47:
                        {
                            Token token = new47(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 48:
                        {
                            Token token = new48(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 49:
                        {
                            Token token = new49(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 50:
                        {
                            Token token = new50(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 51:
                        {
                            Token token = new51(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 52:
                        {
                            Token token = new52(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 53:
                        {
                            Token token = new53(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 54:
                        {
                            Token token = new54(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 55:
                        {
                            Token token = new55(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    }
                }
                else
                {
                    if(text.length() > 0)
                    {
                        throw new LexerException(
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + text);
                    }
                    else
                    {
                        EOF token = new EOF(
                            start_line + 1,
                            start_pos + 1);
                        return token;
                    }
                }
            }
        }
    }

    Token new0(String text, int line, int pos) { return new TComment(text, line, pos); }
    Token new1(int line, int pos) { return new TCommentEnd(line, pos); }
    Token new2(String text, int line, int pos) { return new TCommentBody(text, line, pos); }
    Token new3(int line, int pos) { return new TStar(line, pos); }
    Token new4(int line, int pos) { return new TGreater(line, pos); }
    Token new5(String text, int line, int pos) { return new TString(text, line, pos); }
    Token new6(int line, int pos) { return new TInt(line, pos); }
    Token new7(int line, int pos) { return new TBool(line, pos); }
    Token new8(int line, int pos) { return new TChar(line, pos); }
    Token new9(int line, int pos) { return new TDef(line, pos); }
    Token new10(int line, int pos) { return new TAnd(line, pos); }
    Token new11(int line, int pos) { return new TElse(line, pos); }
    Token new12(int line, int pos) { return new TElsif(line, pos); }
    Token new13(int line, int pos) { return new TEnd(line, pos); }
    Token new14(int line, int pos) { return new TExit(line, pos); }
    Token new15(int line, int pos) { return new TFalse(line, pos); }
    Token new16(int line, int pos) { return new TFor(line, pos); }
    Token new17(int line, int pos) { return new THead(line, pos); }
    Token new18(int line, int pos) { return new TIf(line, pos); }
    Token new19(int line, int pos) { return new TList(line, pos); }
    Token new20(int line, int pos) { return new TMod(line, pos); }
    Token new21(int line, int pos) { return new TNew(line, pos); }
    Token new22(int line, int pos) { return new TNil(line, pos); }
    Token new23(int line, int pos) { return new TNilQuestionMark(line, pos); }
    Token new24(int line, int pos) { return new TNot(line, pos); }
    Token new25(int line, int pos) { return new TOr(line, pos); }
    Token new26(int line, int pos) { return new TRef(line, pos); }
    Token new27(int line, int pos) { return new TReturn(line, pos); }
    Token new28(int line, int pos) { return new TSkip(line, pos); }
    Token new29(int line, int pos) { return new TTail(line, pos); }
    Token new30(int line, int pos) { return new TTrue(line, pos); }
    Token new31(int line, int pos) { return new TDecl(line, pos); }
    Token new32(int line, int pos) { return new TDiv(line, pos); }
    Token new33(int line, int pos) { return new TSharp(line, pos); }
    Token new34(int line, int pos) { return new TSmallerEqual(line, pos); }
    Token new35(int line, int pos) { return new TBiggerEqual(line, pos); }
    Token new36(int line, int pos) { return new TEqual(line, pos); }
    Token new37(int line, int pos) { return new TLPar(line, pos); }
    Token new38(int line, int pos) { return new TRPar(line, pos); }
    Token new39(int line, int pos) { return new TLBr(line, pos); }
    Token new40(int line, int pos) { return new TRBr(line, pos); }
    Token new41(int line, int pos) { return new TComma(line, pos); }
    Token new42(int line, int pos) { return new TSemicolon(line, pos); }
    Token new43(String text, int line, int pos) { return new TColon(text, line, pos); }
    Token new44(int line, int pos) { return new TAssign(line, pos); }
    Token new45(String text, int line, int pos) { return new TBlank(text, line, pos); }
    Token new46(String text, int line, int pos) { return new TLineComment(text, line, pos); }
    Token new47(int line, int pos) { return new TPlus(line, pos); }
    Token new48(int line, int pos) { return new TMinus(line, pos); }
    Token new49(String text, int line, int pos) { return new TConstChar(text, line, pos); }
    Token new50(String text, int line, int pos) { return new TConstInt(text, line, pos); }
    Token new51(String text, int line, int pos) { return new TId(text, line, pos); }
    Token new52(int line, int pos) { return new TMul(line, pos); }
    Token new53(int line, int pos) { return new TNotEqual(line, pos); }
    Token new54(int line, int pos) { return new TSmaller(line, pos); }
    Token new55(int line, int pos) { return new TBigger(line, pos); }

    private int getChar() throws IOException
    {
        if(eof)
        {
            return -1;
        }

        int result = in.read();

        if(result == -1)
        {
            eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            eof = false;

            in.unread(text.charAt(i));
        }
    }

    protected void unread(Token token) throws IOException
    {
        String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            eof = false;

            in.unread(text.charAt(i));
        }

        pos = token.getPos() - 1;
        line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // NORMAL
            {{9, 9, 1}, {10, 10, 2}, {13, 13, 3}, {32, 32, 4}, {34, 34, 5}, {35, 35, 6}, {37, 37, 7}, {39, 39, 8}, {40, 40, 9}, {41, 41, 10}, {42, 42, 11}, {43, 43, 12}, {44, 44, 13}, {45, 45, 14}, {47, 47, 15}, {48, 57, 16}, {58, 58, 17}, {59, 59, 18}, {60, 60, 19}, {61, 61, 20}, {62, 62, 21}, {65, 90, 22}, {91, 91, 23}, {93, 93, 24}, {97, 97, 25}, {98, 98, 26}, {99, 99, 27}, {100, 100, 28}, {101, 101, 29}, {102, 102, 30}, {103, 103, 31}, {104, 104, 32}, {105, 105, 33}, {106, 107, 31}, {108, 108, 34}, {109, 109, 35}, {110, 110, 36}, {111, 111, 37}, {112, 113, 31}, {114, 114, 38}, {115, 115, 39}, {116, 116, 40}, {117, 122, 31}, },
            {},
            {},
            {{10, 10, 41}, },
            {},
            {{0, 9, 42}, {11, 12, 42}, {14, 33, 42}, {34, 34, 43}, {35, 91, 42}, {92, 92, 44}, {93, 127, 42}, },
            {},
            {{0, 9, 45}, {10, 10, 46}, {11, 12, 45}, {13, 13, 47}, {14, 127, 45}, },
            {{48, 57, 48}, {65, 90, 49}, {92, 92, 50}, {97, 122, 51}, },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {{48, 57, 16}, },
            {{61, 61, 52}, },
            {},
            {{42, 42, 53}, {61, 61, 54}, {62, 62, 55}, },
            {},
            {{61, 61, 56}, },
            {{48, 57, 57}, {63, 63, 58}, {65, 90, 59}, {95, 95, 60}, {97, 122, 61}, },
            {},
            {},
            {{48, 95, -24}, {97, 109, 61}, {110, 110, 62}, {111, 122, 61}, },
            {{48, 95, -24}, {97, 110, 61}, {111, 111, 63}, {112, 122, 61}, },
            {{48, 95, -24}, {97, 103, 61}, {104, 104, 64}, {105, 122, 61}, },
            {{48, 95, -24}, {97, 100, 61}, {101, 101, 65}, {102, 122, 61}, },
            {{48, 95, -24}, {97, 107, 61}, {108, 108, 66}, {109, 109, 61}, {110, 110, 67}, {111, 119, 61}, {120, 120, 68}, {121, 122, 61}, },
            {{48, 95, -24}, {97, 97, 69}, {98, 110, 61}, {111, 111, 70}, {112, 122, 61}, },
            {{48, 122, -24}, },
            {{48, 100, -30}, {101, 101, 71}, {102, 122, 61}, },
            {{48, 95, -24}, {97, 101, 61}, {102, 102, 72}, {103, 109, 61}, {110, 110, 73}, {111, 122, 61}, },
            {{48, 95, -24}, {97, 104, 61}, {105, 105, 74}, {106, 122, 61}, },
            {{48, 110, -28}, {111, 111, 75}, {112, 122, 61}, },
            {{48, 100, -30}, {101, 101, 76}, {102, 104, 61}, {105, 105, 77}, {106, 110, 61}, {111, 111, 78}, {112, 122, 61}, },
            {{48, 95, -24}, {97, 113, 61}, {114, 114, 79}, {115, 122, 61}, },
            {{48, 100, -30}, {101, 101, 80}, {102, 122, 61}, },
            {{48, 95, -24}, {97, 106, 61}, {107, 107, 81}, {108, 122, 61}, },
            {{48, 95, -24}, {97, 97, 82}, {98, 113, 61}, {114, 114, 83}, {115, 122, 61}, },
            {},
            {{0, 127, -7}, },
            {},
            {{0, 33, -7}, {34, 34, 84}, {35, 127, -7}, },
            {{0, 127, -9}, },
            {},
            {{10, 10, 85}, },
            {{39, 39, 86}, },
            {{39, 39, 86}, },
            {{34, 34, 87}, {39, 39, 88}, {48, 48, 89}, {92, 92, 90}, {110, 110, 91}, {114, 114, 92}, {116, 116, 93}, {120, 120, 94}, },
            {{39, 39, 86}, },
            {},
            {},
            {},
            {},
            {},
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 95, -24}, {97, 99, 61}, {100, 100, 95}, {101, 122, 61}, },
            {{48, 110, -28}, {111, 111, 96}, {112, 122, 61}, },
            {{48, 95, -24}, {97, 97, 97}, {98, 122, 61}, },
            {{48, 95, -24}, {97, 98, 61}, {99, 99, 98}, {100, 101, 61}, {102, 102, 99}, {103, 122, 61}, },
            {{48, 95, -24}, {97, 114, 61}, {115, 115, 100}, {116, 122, 61}, },
            {{48, 99, -64}, {100, 100, 101}, {101, 122, 61}, },
            {{48, 104, -36}, {105, 105, 102}, {106, 122, 61}, },
            {{48, 107, -31}, {108, 108, 103}, {109, 122, 61}, },
            {{48, 113, -39}, {114, 114, 104}, {115, 122, 61}, },
            {{48, 95, -24}, {97, 97, 105}, {98, 122, 61}, },
            {{48, 122, -24}, },
            {{48, 95, -24}, {97, 115, 61}, {116, 116, 106}, {117, 122, 61}, },
            {{48, 114, -68}, {115, 115, 107}, {116, 122, 61}, },
            {{48, 99, -64}, {100, 100, 108}, {101, 122, 61}, },
            {{48, 95, -24}, {97, 118, 61}, {119, 119, 109}, {120, 122, 61}, },
            {{48, 107, -31}, {108, 108, 110}, {109, 122, 61}, },
            {{48, 115, -75}, {116, 116, 111}, {117, 122, 61}, },
            {{48, 122, -24}, },
            {{48, 101, -35}, {102, 102, 112}, {103, 115, 61}, {116, 116, 113}, {117, 122, 61}, },
            {{48, 104, -36}, {105, 105, 114}, {106, 122, 61}, },
            {{48, 104, -36}, {105, 105, 115}, {106, 122, 61}, },
            {{48, 95, -24}, {97, 116, 61}, {117, 117, 116}, {118, 122, 61}, },
            {{0, 127, -7}, },
            {},
            {},
            {{39, 39, 86}, },
            {{39, 39, 86}, },
            {{39, 39, 86}, },
            {{39, 39, 86}, },
            {{39, 39, 86}, },
            {{39, 39, 86}, },
            {{39, 39, 86}, },
            {{48, 57, 117}, {65, 70, 117}, {97, 102, 117}, },
            {{48, 122, -24}, },
            {{48, 107, -31}, {108, 108, 118}, {109, 122, 61}, },
            {{48, 113, -39}, {114, 114, 119}, {115, 122, 61}, },
            {{48, 107, -31}, {108, 108, 120}, {109, 122, 61}, },
            {{48, 122, -24}, },
            {{48, 100, -30}, {101, 101, 121}, {102, 104, 61}, {105, 105, 122}, {106, 122, 61}, },
            {{48, 122, -24}, },
            {{48, 115, -75}, {116, 116, 123}, {117, 122, 61}, },
            {{48, 114, -68}, {115, 115, 124}, {116, 122, 61}, },
            {{48, 122, -24}, },
            {{48, 99, -64}, {100, 100, 125}, {101, 122, 61}, },
            {{48, 122, -24}, },
            {{48, 115, -75}, {116, 116, 126}, {117, 122, 61}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 57, 57}, {63, 63, 127}, {65, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 116, -85}, {117, 117, 128}, {118, 122, 61}, },
            {{48, 95, -24}, {97, 111, 61}, {112, 112, 129}, {113, 122, 61}, },
            {{48, 107, -31}, {108, 108, 130}, {109, 122, 61}, },
            {{48, 100, -30}, {101, 101, 131}, {102, 122, 61}, },
            {{39, 39, 86}, {48, 57, 132}, {65, 70, 132}, {97, 102, 132}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 101, -35}, {102, 102, 133}, {103, 122, 61}, },
            {{48, 122, -24}, },
            {{48, 100, -30}, {101, 101, 134}, {102, 122, 61}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 113, -39}, {114, 114, 135}, {115, 122, 61}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{39, 39, 86}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 109, -27}, {110, 110, 136}, {111, 122, 61}, },
            {{48, 122, -24}, },
        }
        { // COMMENT
            {{0, 9, 1}, {10, 10, 2}, {11, 12, 1}, {13, 13, 3}, {14, 41, 1}, {42, 42, 4}, {43, 59, 1}, {60, 60, 5}, {61, 61, 1}, {62, 62, 6}, {63, 127, 1}, },
            {{0, 41, -2}, {43, 61, 1}, {63, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 9, 1}, {10, 10, 7}, {11, 127, -3}, },
            {{62, 62, 8}, },
            {{0, 41, -2}, {42, 42, 9}, {43, 127, -3}, },
            {},
            {{0, 127, -3}, },
            {},
            {},
        }
    };*/

    private static int[][] accept;
/*  {
        // NORMAL
        {-1, 45, 45, 45, 45, -1, 33, -1, -1, 37, 38, 52, 47, 41, 48, 32, 50, 43, 42, 54, 36, 55, 51, 39, 40, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 45, -1, 5, -1, -1, 46, 46, -1, -1, -1, -1, 44, 0, 34, 53, 35, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 18, 51, 51, 51, 51, 51, 51, 25, 51, 51, 51, 51, 5, 46, 49, -1, -1, -1, -1, -1, -1, -1, -1, 10, 51, 51, 51, 9, 51, 13, 51, 51, 16, 51, 6, 51, 20, 21, 22, 24, 26, 51, 51, 51, 51, -1, 7, 8, 31, 11, 51, 14, 51, 17, 19, 23, 51, 28, 29, 30, -1, 12, 15, 51, 27, },
        // COMMENT
        {2, 2, 2, 2, 3, 2, 4, 2, 1, 0, },

    };*/

    public static class State
    {
        public final static State NORMAL = new State(0);
        public final static State COMMENT = new State(1);

        private int id;

        private State(int id)
        {
            this.id = id;
        }

        public int id()
        {
            return id;
        }
    }
}
